'use strict';
import mongoose from 'mongoose';

const { Schema } = mongoose;

const carouselSlideSchema = new Schema(
  {
    customerId: {
      type: Schema.Types.ObjectId,
      ref: 'Customer',
      required: true,
    },
    companyName: { type: String, required: true, trim: true, maxlength: 120 },
    companyWebsite: { type: String, trim: true, maxlength: 255, default: '' },
    companyPhone: { type: String, trim: true, maxlength: 30, default: '' },
    companyDescription: {
      type: String,
      trim: true,
      maxlength: 500,
      default: '',
    },
    picturePath: { type: String, required: true },
    picture2Path: { type: String, default: '' },
    picture2PositionX: { type: Number, min: 0, max: 100, default: 72 },
    picture2PositionY: { type: Number, min: 0, max: 100, default: 72 },
    picture2Scale: { type: Number, min: 20, max: 160, default: 100 },
    linkUrl: { type: String, trim: true, maxlength: 255, default: '' },
    animationEnabled: { type: Boolean, default: false },
    imageScale: { type: Number, min: 20, max: 160, default: 100 },
    imageFitMode: {
      type: String,
      enum: ['contain', 'cover'],
      default: 'contain',
    },
    imagePositionX: { type: Number, min: 0, max: 100, default: 50 },
    imagePositionY: { type: Number, min: 0, max: 100, default: 50 },
    captionPositionX: { type: Number, min: 0, max: 100, default: 0 },
    captionPositionY: { type: Number, min: 0, max: 100, default: 0 },
    captionWidthPct: { type: Number, min: 5, max: 100, default: 30 },
    captionHeightPct: { type: Number, min: 10, max: 100, default: 30 },
    descriptionPositionX: { type: Number, min: 0, max: 100, default: 50 },
    descriptionPositionY: { type: Number, min: 0, max: 100, default: 78 },
    captionFontColor: {
      type: String,
      trim: true,
      maxlength: 30,
      default: '#ffffff',
    },
    captionFontSize: { type: Number, min: 10, max: 48, default: 16 },
    captionFontWeight: {
      type: String,
      enum: ['400', '600', '700', '900'],
      default: '600',
    },
    descriptionFontColor: {
      type: String,
      trim: true,
      maxlength: 30,
      default: '#ffffff',
    },
    descriptionFontSize: { type: Number, min: 10, max: 48, default: 14 },
    descriptionFontWeight: {
      type: String,
      enum: ['400', '600', '700', '900'],
      default: '400',
    },
    descriptionBgColor: {
      type: String,
      trim: true,
      maxlength: 30,
      default: '#000000',
    },
    slideBgColor: { type: String, trim: true, maxlength: 30, default: '' },
    status: {
      type: String,
      enum: ['pending', 'approved', 'active', 'paused', 'expired', 'cancelled'],
      default: 'pending',
    },
    maxChargeLimit: { type: Number, min: 0, default: null },
    billingCapApprovalPending: { type: Boolean, default: false },
    billingCapApprovalRequestedAt: { type: Date, default: null },
    billingCapApprovalGrantedAt: { type: Date, default: null },
    billingCapOverrideUntil: { type: Date, default: null },
    billingCapReachedAt: { type: Date, default: null },
    impressionsTotal: { type: Number, min: 0, default: 0 },
    impressionsBilled: { type: Number, min: 0, default: 0 },
    spendAccruedCents: { type: Number, min: 0, default: 0 },
    currentPeriodStartedAt: { type: Date, default: null },
    stripePaymentIntentId: { type: String, default: '' },
    stripePaymentMethodId: { type: String, default: '' },
    stripeCustomerId: { type: String, default: '' },
    pendingAuthPaymentIntentId: { type: String, default: '' },
    expiresAt: { type: Date, default: null },
    paidAt: { type: Date, default: null },
    inactiveSince: { type: Date, default: null },
  },
  { timestamps: true },
);

export default mongoose.model('CarouselSlide', carouselSlideSchema);
